# Generated by Django 4.1.1 on 2022-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
