# Generated by Django 4.1.1 on 2022-09-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_contato_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_contatos/%Y/%m/%d'),
        ),
    ]
